Use AWS version 5.X
silinternational/app-monitoring-archiver pull request #56
Opened 2024-10-11 21:15 UTC by jason-jackson

### Changed
- Upgrade to AWS version 5.X

2024-10-12 00:47 UTC, briskt commented
The lock file should be updated using `terraform init -upgrade`. You can add the `-backend=false` flag to avoid interacting with the remote backend on HCP Terraform (Terraform Cloud).

2024-10-12 02:19 UTC, jason-jackson commented
> The lock file should be updated using `terraform init -upgrade`. You can add the `-backend=false` flag to avoid interacting with the remote backend on HCP Terraform (Terraform Cloud).

I'll sync with you or Matt next week as I ran into issues with that.

2024-10-13 00:04 UTC, mtompset approved these changes

2024-10-13 23:56 UTC, briskt requested changes

2024-10-13 23:56 UTC, briskt commented on terraform/versions.tf
> +      version = "~> 5.0"
Since the serverless-user module has already been updated to use AWS version 5 in a later version ([0.4.0](https://github.com/silinternational/terraform-aws-serverless-user/releases/tag/0.4.0)) it's simply a matter of specifying that version or later in the module version line (main.tf:7) like this:

```hcl
module "serverless-user" {
  source  = "silinternational/serverless-user/aws"
  version = "~> 0.4"

  app_name   = "app-monitoring-archiver"
}
```

Note that I also removed the `aws_region` input because it was removed in version 0.4.1. It is rarely necessary to pass the region as an input since it's implicit in the AWS provider definition passed into each module that uses AWS.

2024-11-05 19:03 UTC, forevermatt approved these changes

2024-11-06 01:09 UTC, briskt approved these changes
Looks good. You could remove the version constraint if you want. I think I wasn't aware of that level of optimization when I first reviewed this PR.

2024-11-06 05:17 UTC, merged